name: Build and push the docker image/s

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Check for build-tools changes
        id: git-diff
        uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            build-tools/**
      -
        name: Build and push build-tools image
        if: steps.git-diff.outputs.count > 0
        uses: docker/build-push-action@v2
        with:
          context: build-tools/
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
           debricked/docker-image-build-tools:latest
           ghcr.io/debricked/docker-image-build-tools:latest
      -
        name: Build and push full image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
           debricked/docker-image-php-xdebug:latest
           ghcr.io/debricked/docker-image-php-xdebug:latest
